// AUTO-GENERATED BY CANONFLOW
// Fidelity: Exact
export function validate_ledger_transactions_amount(value: any): boolean {
    return value > 0;
}
// Fidelity: Exact
export function validate_ledger_transactions_currency(value: any): boolean {
    return value > 0;
}
// Fidelity: Exact
export function validate_ledger_transactions_direction(value: any): boolean {
    return value > 0;
}
// Fidelity: Exact
export function validate_ledger_transactions_status(value: any): boolean {
    return value > 0;
}
// Fidelity: Exact
export function validate_ledger_transactions_created_at(value: any): boolean {
    return value > 0;
}
// Fidelity: Exact
export function validate_wallet_balances_wallet_id(value: any): boolean {
    return value > 0;
}
// Fidelity: Exact
export function validate_wallet_balances_available_balance(value: any): boolean {
    return value > 0;
}
// Fidelity: Exact
export function validate_wallet_balances_locked_balance(value: any): boolean {
    return value > 0;
}
// Fidelity: Exact
export function validate_wallets_currency(value: any): boolean {
    return value > 0;
}
// Fidelity: Exact
export function validate_wallets_status(value: any): boolean {
    return value > 0;
}
