
import { StringBuilder__AppendLine, StringBuilder__AppendLine_Z721C83C5, StringBuilder_$ctor } from "../fable_modules/fable-library-js.5.6.0/System.Text.js";
import { FSharpMap__get_Item, FSharpMap__ContainsKey, ofList } from "../fable_modules/fable-library-js.5.6.0/Map.js";
import { map } from "../fable_modules/fable-library-js.5.6.0/List.js";
import { equals, disposeSafe, getEnumerator, comparePrimitives } from "../fable_modules/fable-library-js.5.6.0/Util.js";
import { join, concat } from "../fable_modules/fable-library-js.5.6.0/String.js";
import { toString } from "../fable_modules/fable-library-js.5.6.0/Types.js";

export function generateMigration(oldSchema, newSchema) {
    const sb = StringBuilder_$ctor();
    StringBuilder__AppendLine_Z721C83C5(sb, "-- AUTO-GENERATED BY CANONFLOW MIGRATION ENGINE");
    StringBuilder__AppendLine_Z721C83C5(sb, "BEGIN;");
    StringBuilder__AppendLine(sb);
    const oldMap = ofList(map((t) => [t.Name, t], oldSchema), {
        Compare: (x, y) => (comparePrimitives(x, y) | 0),
    });
    const newMap = ofList(map((t_1) => [t_1.Name, t_1], newSchema), {
        Compare: (x_1, y_1) => (comparePrimitives(x_1, y_1) | 0),
    });
    const enumerator = getEnumerator(oldMap);
    try {
        while (enumerator["System.Collections.IEnumerator.MoveNext"]()) {
            const kvp = enumerator["System.Collections.Generic.IEnumerator`1.get_Current"]();
            if (!FSharpMap__ContainsKey(newMap, kvp[0])) {
                StringBuilder__AppendLine_Z721C83C5(sb, concat("DROP TABLE public.", kvp[0], " CASCADE;"));
            }
        }
    }
    finally {
        disposeSafe(enumerator);
    }
    const enumerator_1 = getEnumerator(newMap);
    try {
        while (enumerator_1["System.Collections.IEnumerator.MoveNext"]()) {
            const kvp_1 = enumerator_1["System.Collections.Generic.IEnumerator`1.get_Current"]();
            if (!FSharpMap__ContainsKey(oldMap, kvp_1[0])) {
                const t_2 = kvp_1[1];
                StringBuilder__AppendLine_Z721C83C5(sb, concat("CREATE TABLE public.", t_2.Name, " ("));
                StringBuilder__AppendLine_Z721C83C5(sb, join(",\n", map((c) => (`    ${c.Name} ${c.DataType}${c.IsNullable ? "" : " NOT NULL"}${c.IsPrimaryKey ? " PRIMARY KEY" : ""}`), t_2.Columns)));
                StringBuilder__AppendLine_Z721C83C5(sb, ");");
            }
        }
    }
    finally {
        disposeSafe(enumerator_1);
    }
    const enumerator_2 = getEnumerator(newMap);
    try {
        while (enumerator_2["System.Collections.IEnumerator.MoveNext"]()) {
            const kvp_2 = enumerator_2["System.Collections.Generic.IEnumerator`1.get_Current"]();
            if (FSharpMap__ContainsKey(oldMap, kvp_2[0])) {
                const oldT = FSharpMap__get_Item(oldMap, kvp_2[0]);
                const newT = kvp_2[1];
                const oldCols = ofList(map((c_1) => [c_1.Name, c_1], oldT.Columns), {
                    Compare: (x_2, y_2) => (comparePrimitives(x_2, y_2) | 0),
                });
                const newCols = ofList(map((c_2) => [c_2.Name, c_2], newT.Columns), {
                    Compare: (x_3, y_3) => (comparePrimitives(x_3, y_3) | 0),
                });
                const enumerator_3 = getEnumerator(oldCols);
                try {
                    while (enumerator_3["System.Collections.IEnumerator.MoveNext"]()) {
                        const oldC = enumerator_3["System.Collections.Generic.IEnumerator`1.get_Current"]();
                        if (!FSharpMap__ContainsKey(newCols, oldC[0])) {
                            StringBuilder__AppendLine_Z721C83C5(sb, `ALTER TABLE public.${newT.Name} DROP COLUMN ${oldC[0]};`);
                        }
                    }
                }
                finally {
                    disposeSafe(enumerator_3);
                }
                const enumerator_4 = getEnumerator(newCols);
                try {
                    while (enumerator_4["System.Collections.IEnumerator.MoveNext"]()) {
                        const newC = enumerator_4["System.Collections.Generic.IEnumerator`1.get_Current"]();
                        if (!FSharpMap__ContainsKey(oldCols, newC[0])) {
                            const c_3 = newC[1];
                            StringBuilder__AppendLine_Z721C83C5(sb, `ALTER TABLE public.${newT.Name} ADD COLUMN ${c_3.Name} ${c_3.DataType}${c_3.IsNullable ? "" : " NOT NULL"};`);
                        }
                        else {
                            const nC = newC[1];
                            if (FSharpMap__get_Item(oldCols, newC[0]).DataType !== nC.DataType) {
                                StringBuilder__AppendLine_Z721C83C5(sb, `ALTER TABLE public.${newT.Name} ALTER COLUMN ${nC.Name} TYPE ${nC.DataType} USING ${nC.Name}::${nC.DataType};`);
                            }
                        }
                    }
                }
                finally {
                    disposeSafe(enumerator_4);
                }
                if (!equals(oldT.TableConstraints, newT.TableConstraints)) {
                    StringBuilder__AppendLine_Z721C83C5(sb, concat("-- WARNING: Constraints drift detected in table ", newT.Name, ". Manual migration of CHECK bounds required."));
                }
            }
        }
    }
    finally {
        disposeSafe(enumerator_2);
    }
    StringBuilder__AppendLine(sb);
    StringBuilder__AppendLine_Z721C83C5(sb, "COMMIT;");
    return toString(sb);
}

