module CanonFlowRest.Api
open Giraffe
open Microsoft.AspNetCore.Http
open Npgsql
open Dapper
open System.Threading.Tasks

// AUTO-GENERATED BY CANONFLOWREST
// These endpoints provide Noun-level CRUD backed by the DB boundaries.
// For complex workflows (Verbs), implement custom Handlers below.

let getcustomersHandler (connString: string) : HttpHandler =
    fun (next : HttpFunc) (ctx : HttpContext) ->
        task {
            use conn = new NpgsqlConnection(connString)
            let! jsonResult = conn.QuerySingleOrDefaultAsync<string>("SELECT COALESCE(json_agg(row_to_json(t)), '[]') FROM customers t")
            let result = if System.String.IsNullOrEmpty(jsonResult) then "[]" else jsonResult
            ctx.SetHttpHeader("Content-Type", "application/json")
            return! ctx.WriteStringAsync(result)
        }

let postcustomersHandler (connString: string) : HttpHandler =
    fun (next : HttpFunc) (ctx : HttpContext) ->
        task {
            // OVERRIDE FOR DDD VERBS
            // Parse JSON payload into DTO, run DDD logic, and INSERT.
            ctx.SetStatusCode 501
            return! text "POST /customers - Auto-Insert Not Fully Implemented (Override Here)" next ctx
        }

let getordersHandler (connString: string) : HttpHandler =
    fun (next : HttpFunc) (ctx : HttpContext) ->
        task {
            use conn = new NpgsqlConnection(connString)
            let! jsonResult = conn.QuerySingleOrDefaultAsync<string>("SELECT COALESCE(json_agg(row_to_json(t)), '[]') FROM orders t")
            let result = if System.String.IsNullOrEmpty(jsonResult) then "[]" else jsonResult
            ctx.SetHttpHeader("Content-Type", "application/json")
            return! ctx.WriteStringAsync(result)
        }

let postordersHandler (connString: string) : HttpHandler =
    fun (next : HttpFunc) (ctx : HttpContext) ->
        task {
            // OVERRIDE FOR DDD VERBS
            // Parse JSON payload into DTO, run DDD logic, and INSERT.
            ctx.SetStatusCode 501
            return! text "POST /orders - Auto-Insert Not Fully Implemented (Override Here)" next ctx
        }


let webApp (connectionString: string) =
    choose [
        route "/api/customers" >=> choose [
            GET >=> getcustomersHandler connectionString
            POST >=> postcustomersHandler connectionString
        ]
        route "/api/orders" >=> choose [
            GET >=> getordersHandler connectionString
            POST >=> postordersHandler connectionString
        ]
        setStatusCode 404 >=> text "Not Found"
    ]
